//
// Created by shaob on 2020/2/23.
//

#ifndef UNRESTRAINEDGAMBLINGWITHSURREPTITIOUSLUNA_PATMAINHEADER_H
#define UNRESTRAINEDGAMBLINGWITHSURREPTITIOUSLUNA_PATMAINHEADER_H

int pat_solver();


#endif //UNRESTRAINEDGAMBLINGWITHSURREPTITIOUSLUNA_PATMAINHEADER_H
