//
// Created by shaob on 2020/2/23.
//

#ifndef UNRESTRAINEDGAMBLINGWITHSURREPTITIOUSLUNA_ALGNOTEMAINHEADER_H
#define UNRESTRAINEDGAMBLINGWITHSURREPTITIOUSLUNA_ALGNOTEMAINHEADER_H

int alg_solver();

#endif //UNRESTRAINEDGAMBLINGWITHSURREPTITIOUSLUNA_ALGNOTEMAINHEADER_H
